// <auto-generated />
using System;
using CarTrack.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarTrack.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarTrack.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accent_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean")
                        .HasColumnName("favorite");

                    b.Property<bool>("IsElectric")
                        .HasColumnType("boolean")
                        .HasColumnName("is_electric");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_plate");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("model");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vin");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_cars");

                    b.ToTable("cars", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarDocument", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("CarId", "DocumentId")
                        .HasName("pk_car_documents");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_car_documents_document_id");

                    b.ToTable("car_documents", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarPicture", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("PictureId")
                        .HasColumnType("uuid")
                        .HasColumnName("picture_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("CarId", "PictureId")
                        .HasName("pk_car_pictures");

                    b.HasIndex("PictureId")
                        .HasDatabaseName("ix_car_pictures_picture_id");

                    b.ToTable("car_pictures", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarShare", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RedeemedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redeemed_at");

                    b.Property<Guid?>("RedeemedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("redeemed_by");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_car_shares");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_car_shares_car_id");

                    b.HasIndex("RedeemedBy")
                        .HasDatabaseName("ix_car_shares_redeemed_by");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_car_shares_token");

                    b.ToTable("car_shares", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarUser", b =>
                {
                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("CarId", "UserId")
                        .HasName("pk_car_users");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_car_users_user_id");

                    b.ToTable("car_users", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.DocumentKind", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Slug")
                        .HasName("pk_document_kinds");

                    b.ToTable("document_kinds", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "rca",
                            IsSystem = true,
                            Label = "RCA Insurance",
                            SortOrder = 0
                        },
                        new
                        {
                            Slug = "cartea-verde",
                            IsSystem = true,
                            Label = "Cartea Verde",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.DocumentPicture", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("PictureId")
                        .HasColumnType("uuid")
                        .HasColumnName("picture_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("DocumentId", "PictureId")
                        .HasName("pk_document_pictures");

                    b.HasIndex("PictureId")
                        .HasDatabaseName("ix_document_pictures_picture_id");

                    b.ToTable("document_pictures", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("category");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CarId")
                        .HasDatabaseName("ix_expenses_car_id");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator<string>("Category").HasValue("Expense");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.ExpenseCategory", b =>
                {
                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Icon")
                        .HasColumnType("text")
                        .HasColumnName("icon");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Slug")
                        .HasName("pk_expense_categories");

                    b.ToTable("expense_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Slug = "fuel",
                            IsSystem = true,
                            Label = "Fuel",
                            SortOrder = 0
                        },
                        new
                        {
                            Slug = "repair",
                            IsSystem = true,
                            Label = "Repair",
                            SortOrder = 1
                        },
                        new
                        {
                            Slug = "parts",
                            IsSystem = true,
                            Label = "Parts",
                            SortOrder = 2
                        },
                        new
                        {
                            Slug = "inspection",
                            IsSystem = true,
                            Label = "Inspection",
                            SortOrder = 3
                        },
                        new
                        {
                            Slug = "other",
                            IsSystem = true,
                            Label = "Other",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.Picture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("object_key");

                    b.Property<int?>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.HasKey("Id")
                        .HasName("pk_pictures");

                    b.ToTable("pictures", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.VehicleDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Insurer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("insurer");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_vehicle_documents");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_vehicle_documents_kind");

                    b.ToTable("vehicle_documents", (string)null);
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.FuelExpense", b =>
                {
                    b.HasBaseType("CarTrack.Domain.Entities.Expense");

                    b.Property<decimal>("FuelQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel_quantity");

                    b.Property<string>("FuelUnit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fuel_unit");

                    b.Property<decimal>("FuelUnitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("fuel_unit_price");

                    b.Property<int?>("OdometerKm")
                        .HasColumnType("integer")
                        .HasColumnName("odometer_km");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator().HasValue("fuel");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.InspectionExpense", b =>
                {
                    b.HasBaseType("CarTrack.Domain.Entities.Expense");

                    b.Property<DateOnly?>("NextDueDate")
                        .HasColumnType("date")
                        .HasColumnName("next_due_date");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator().HasValue("inspection");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.OtherExpense", b =>
                {
                    b.HasBaseType("CarTrack.Domain.Entities.Expense");

                    b.Property<string>("OtherDescription")
                        .HasColumnType("text")
                        .HasColumnName("other_description");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator().HasValue("other");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.PartsExpense", b =>
                {
                    b.HasBaseType("CarTrack.Domain.Entities.Expense");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("part_name");

                    b.Property<int>("PartsQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("parts_quantity");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator().HasValue("parts");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.RepairExpense", b =>
                {
                    b.HasBaseType("CarTrack.Domain.Entities.Expense");

                    b.Property<string>("Mechanic")
                        .HasColumnType("text")
                        .HasColumnName("mechanic");

                    b.Property<string>("RepairDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("repair_description");

                    b.ToTable("expenses", (string)null);

                    b.HasDiscriminator().HasValue("repair");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarDocument", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.Car", "Car")
                        .WithMany("CarDocuments")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_documents_cars_car_id");

                    b.HasOne("CarTrack.Domain.Entities.VehicleDocument", "Document")
                        .WithMany("CarDocuments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_documents_vehicle_documents_document_id");

                    b.Navigation("Car");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarPicture", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.Car", "Car")
                        .WithMany("CarPictures")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_pictures_cars_car_id");

                    b.HasOne("CarTrack.Domain.Entities.Picture", "Picture")
                        .WithMany("CarPictures")
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_pictures_pictures_picture_id");

                    b.Navigation("Car");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarShare", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.Car", "Car")
                        .WithMany("CarShares")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_shares_cars_car_id");

                    b.HasOne("CarTrack.Domain.Entities.User", "RedeemedByUser")
                        .WithMany()
                        .HasForeignKey("RedeemedBy")
                        .HasConstraintName("fk_car_shares_users_redeemed_by");

                    b.Navigation("Car");

                    b.Navigation("RedeemedByUser");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.CarUser", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.Car", "Car")
                        .WithMany("CarUsers")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_users_cars_car_id");

                    b.HasOne("CarTrack.Domain.Entities.User", "User")
                        .WithMany("CarUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_car_users_users_user_id");

                    b.Navigation("Car");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.DocumentPicture", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.VehicleDocument", "Document")
                        .WithMany("DocumentPictures")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_pictures_vehicle_documents_document_id");

                    b.HasOne("CarTrack.Domain.Entities.Picture", "Picture")
                        .WithMany("DocumentPictures")
                        .HasForeignKey("PictureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_pictures_pictures_picture_id");

                    b.Navigation("Document");

                    b.Navigation("Picture");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.Expense", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.Car", "Car")
                        .WithMany("Expenses")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_cars_car_id");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.VehicleDocument", b =>
                {
                    b.HasOne("CarTrack.Domain.Entities.DocumentKind", "KindNavigation")
                        .WithMany()
                        .HasForeignKey("Kind")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicle_documents_document_kinds_kind");

                    b.Navigation("KindNavigation");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.Car", b =>
                {
                    b.Navigation("CarDocuments");

                    b.Navigation("CarPictures");

                    b.Navigation("CarShares");

                    b.Navigation("CarUsers");

                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.Picture", b =>
                {
                    b.Navigation("CarPictures");

                    b.Navigation("DocumentPictures");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.User", b =>
                {
                    b.Navigation("CarUsers");

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("CarTrack.Domain.Entities.VehicleDocument", b =>
                {
                    b.Navigation("CarDocuments");

                    b.Navigation("DocumentPictures");
                });
#pragma warning restore 612, 618
        }
    }
}
